### ISSUE TITLE
no module named "rbf.poly"

### ISSUE THREAD

**Issue by remoss96CZ** [treverhines/RBF#17]
hello,
when i try to run one of your examples the python sends this error: 

Reloaded modules: rbf._version, rbf
Traceback (most recent call last):

  File "C:\Users\frant\Desktop\RSM_v5\untitled2.py", line 9, in <module>
    from rbf.basis import mq

  File "C:\Users\frant\rbf\basis.py", line 60, in <module>
    from rbf.poly import monomial_powers

ModuleNotFoundError: No module named 'rbf.poly'

can you please help me?

**Comment by remoss96CZ** [comment]
problem solved. i just needed to execute the script from another directory.
